/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIChannel;
interface nsIInputStream;

[scriptable, uuid(9bd368b6-3893-4fd7-b7e7-40a9cd45e684)]
interface nsIAlternateSourceChannel : nsISupports {
  void forwardToOriginalChannel();
  void initiateAlternateResponse(in nsIInputStream body);
  readonly attribute nsIChannel wrappedChannel;
};
